
### Get all social refs
GET {{BASE_URL}}/v1/social-ref
Authorization: Bearer {{ACCESS_TOKEN2}}
Accept: application/json
Accept-Language: {{LANG}}

### Get social link
GET {{BASE_URL}}/v1/social-ref/6161d5887bf8af9a59cee5f1
Authorization: Bearer {{ACCESS_TOKEN2}}
Accept: application/json
Accept-Language: {{LANG}}

### Add social ref
POST {{BASE_URL}}/v1/social-ref
Authorization: Bearer {{ACCESS_TOKEN2}}
Accept: application/json
Accept-Language: {{LANG}}
Content-Type: application/json

{
   "label": "FB", 
   "slug": "sakam_aakash",
   "socialServiceKey": "g6q1alqf"
}

### Update social ref
PUT {{BASE_URL}}/v1/social-ref/6161d5887bf8af9a59cee5f1
Authorization: Bearer {{ACCESS_TOKEN2}}
Accept: application/json
Accept-Language: {{LANG}}
Content-Type: application/json

{
   "label": "FB Account"
}

### Delete social ref
DELETE {{BASE_URL}}/v1/social-ref/616035848f64a2961c43b48b
Authorization: Bearer {{ACCESS_TOKEN2}}
Accept: application/json
Accept-Language: {{LANG}}
Content-Type: application/json
