
### Create new user
POST {{BASE_URL}}/v1/user/register
Accept: application/json
Accept-Language: {{LANG}}
Content-Type: application/json

# {
#    "username": "rajat",
#    "fullname": "Rajat Sharma",
#    "email": "rajat@developar.in",
#    "password": "test1010"
# }

{
   "username": "aakash",
   "fullname": "Aakash Sisodiya",
   "email": "aakash@developar.in",
   "password": "aakash2709"
}

### Get access token
POST {{BASE_URL}}/v1/user/token
Accept: application/json
Accept-Language: {{LANG}}
Content-Type: application/json

# {
#    "email": "rajat@developar.in",
#    "password": "test1010"
# }

{
   "username": "aakash",
   "password": "aakash2709"
}
