
CREATE TABLE IF NOT EXISTS users(
   id INT(8) PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(30) UNIQUE NOT NULL,
   email VARCHAR(320) UNIQUE NOT NULL,
   email_verified BIT(1) DEFAULT 0,
   password_hash TEXT NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
